# Header

menu:
  主页: /
  归档: /archives

# SubNav
subnav:
  github: "https://github.com/coolcao"
  weibo: "http://weibo.com/1946282212"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  #mail: ""
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: http://7xt3oh.com2.z0.glb.clouddn.com/CC2.png

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  # friends: '友链'
  aboutme: '关于我'

# friends:
#   友情链接1: http://localhost:4000/
#   友情链接2: http://localhost:4000/
#   友情链接3: http://localhost:4000/
#   友情链接4: http://localhost:4000/
#   友情链接5: http://localhost:4000/
#   友情链接6: http://localhost:4000/

aboutme: coolcao<br/><br/>nodejs工程师<br/><br/>为全栈目标不断努力<br/><br/>