language: node_js
node_js:
- 6.9.1
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_3649a89f32c4_key -iv $encrypted_3649a89f32c4_iv
  -in id_rsa_travis.enc -out ~\/.ssh/id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa_travis
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_travis
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "coolcao"
- git config --global user.email "me@coolcao.com"
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
